Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,8 +26,7 @@ jobs:
       uses: docker/setup-buildx-action@v3
 
     - name: Create builder and use it
-      run: |
-        docker buildx create --use
+      run: docker buildx create --use
 
     - name: Install QEMU for multi-arch support
       uses: docker/setup-qemu-action@v3
@@ -51,8 +50,7 @@ jobs:
         done
 
     - name: List Files for Debugging
-      run: |
-        ls -lh
+      run: ls -lh
 
     - name: Determine file handling logic
       id: determine_logic
@@ -62,8 +60,7 @@ jobs:
         num_images=${#image_array[@]}
 
         if [ $num_images -eq 1 ]; then
-          original_file="${image_array[0]%%:*}"
-          original_file="${original_file##*/}.tar"
+          original_file="${image_array[0]%%:*}.tar"
           echo "ORIGINAL_FILE=${original_file}" >> $GITHUB_ENV
           if [ -z "${{ github.event.inputs.custom_name }}" ]; then
             custom_file="$original_file"
@@ -81,12 +78,23 @@ jobs:
 
     - name: Compress if necessary
       if: steps.determine_logic.outputs.num_images > 1
+      run: tar -czf "${{ env.CUSTOM_FILE }}" *.tar
+
+    - name: Rename file just before file size check
+      if: steps.determine_logic.outputs.num_images == 1
       run: |
-        tar -czf "${{ env.CUSTOM_FILE }}" *.tar
+        if [ "${{ env.ORIGINAL_FILE }}" != "${{ env.CUSTOM_FILE }}" ]; then
+          mv "${{ env.ORIGINAL_FILE }}" "${{ env.CUSTOM_FILE }}"
+        fi
+        ls -lh
 
     - name: Check file size
       run: |
         file="${{ env.CUSTOM_FILE }}"
+        if [ ! -f "$file" ]; then
+          echo "File not found!"
+          exit 1
+        fi
         file_size=$(stat -c%s "$file")
         max_size=$((2 * 1024 * 1024 * 1024))
 
@@ -96,25 +104,8 @@ jobs:
           echo "EXCEEDS_LIMIT=false" >> $GITHUB_ENV
         fi
 
-    - name: Rename file just before upload (if needed)
-      if: steps.determine_logic.outputs.num_images == 1
-      run: |
-        if [ "${{ env.ORIGINAL_FILE }}" != "${{ env.CUSTOM_FILE }}" ]; then
-          mv "${{ env.ORIGINAL_FILE }}" "${{ env.CUSTOM_FILE }}"
-        fi
-        ls -lh  # Double-check the files
-
-    - name: Verify file for upload
-      run: |
-        if [ ! -f "${{ env.CUSTOM_FILE }}" ]; then
-          echo "File not found!"
-          exit 1
-        fi
-
     - name: Get release name and tag
       run: |
-        release_name="${{ env.CUSTOM_FILE }}"
-        
         if [ -z "${{ github.event.inputs.tag }}" ]; then
           tag_name=$(date +'%Y%m%d')
         else
@@ -123,7 +114,7 @@ jobs:
         echo "RELEASE_TAG=$tag_name" >> $GITHUB_ENV
 
     - name: Upload to GitHub Release (if under 2GB)
-      if: env.EXCEEDS_LIMIT == 'false' && steps.verify_file.outputs.result == 'success'
+      if: env.EXCEEDS_LIMIT == 'false'
       uses: softprops/action-gh-release@v1
       with:
         tag_name: ${{ env.RELEASE_TAG }}
@@ -138,7 +129,5 @@ jobs:
         name: ${{ env.CUSTOM_FILE }}
         path: ${{ env.CUSTOM_FILE }}
 
-    - name: Clean up intermediate files (if under 2GB)
-      if: env.EXCEEDS_LIMIT == 'false'
-      run: |
-        rm *.tar
+    - name: Clean up intermediate files
+      run: rm *.tar*
